//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away Team.
        /// </summary>
        public static string strAway {
            get {
                return ResourceManager.GetString("strAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards:.
        /// </summary>
        public static string strCards {
            get {
                return ResourceManager.GetString("strCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your resolution.
        /// </summary>
        public static string strChooseRes {
            get {
                return ResourceManager.GetString("strChooseRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string strClose {
            get {
                return ResourceManager.GetString("strClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference:.
        /// </summary>
        public static string strDifference {
            get {
                return ResourceManager.GetString("strDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string strDraw {
            get {
                return ResourceManager.GetString("strDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen?.
        /// </summary>
        public static string strFullScr {
            get {
                return ResourceManager.GetString("strFullScr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        public static string strGoal {
            get {
                return ResourceManager.GetString("strGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string strGoals {
            get {
                return ResourceManager.GetString("strGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Team.
        /// </summary>
        public static string strHome {
            get {
                return ResourceManager.GetString("strHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loses:.
        /// </summary>
        public static string strLose {
            get {
                return ResourceManager.GetString("strLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string strMatches {
            get {
                return ResourceManager.GetString("strMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string strNext {
            get {
                return ResourceManager.GetString("strNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string strNumber {
            get {
                return ResourceManager.GetString("strNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received:.
        /// </summary>
        public static string strReceived {
            get {
                return ResourceManager.GetString("strReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scored:.
        /// </summary>
        public static string strScored {
            get {
                return ResourceManager.GetString("strScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set picture.
        /// </summary>
        public static string strSetPic {
            get {
                return ResourceManager.GetString("strSetPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won:.
        /// </summary>
        public static string strWon {
            get {
                return ResourceManager.GetString("strWon", resourceCulture);
            }
        }
    }
}
